### ISSUE TITLE
Feature proposal: Funky Friday 

### ISSUE THREAD

**Issue by OurBoy22** [eli-samuel/X-BOT#5]
Estimated points: 1
Priority: vital

Task Breakdown:
- Implement code that whenever a message is sent, bot checks if message has been sent this friday (checks for a boolean). If the message has not been sent, sends the link. 
- Have the Boolean reset every Monday or so.

Risks:
- None, this is awesome

Countermeasures:
- The epicness of this the link will be the sole countermeasure

Notes:
- Link in question: https://cdn.discordapp.com/attachments/686480561946099713/1089223084877283428/trim.9E58D6F8-F40F-4730-B129-5113F304C098.mov

**Comment by eli-samuel** [comment]
oops
